branch-defaults:
  develop:
    environment: develop
global:
  application_name: trendist
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Ruby 2.3 (Puma)
  default_region: ap-northeast-2
  profile: eb-cli
  sc: git
